---
- hosts: all
  become: yes
  tasks:
  - name: Install the "apache"
    apt:
      name: apache2
      state: present

  - name: Start service httpd, if not running
    service:
      name: apache2
      state: restarted 