---
- hosts: mywebservers
  become: yes
  tasks:
  - name: Install the "apache"
    apt:
      name: "{{mypackageofjavaonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: Install the "webserver"
    yum:
      name: "{{mypackageofjavaonredHat}}"
      state: present
    when: ansible_os_family =="RedHat" 