---
- hosts: all
  become: yes
  tasks:
  - name: Install the "apache"
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"

  - name: Start service httpd, if not running
    service:
      name: apache2
      state: restarted 
    when: ansible_os_family =="Debian"

  - name: Install the "apache"
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Redhat"

  - name: Start service httpd, if not running
    service:
      name: apache2
      state: restarted 
    when: ansible_os_family =="Redhat"  